# --- signifies a yml file
# push - trigger to run the jobs
# runs-on - os to run the job ubintu come with docker compose
# actions/checkout@v2 - checks the code out
---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm ton-restaurant sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm ton-restaurant sh -c "flake8"